<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class KomponenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('komponen')->insert([
            [
                'kode_komponen' => 'J02SMRL1001',
                'nama_komponen' => 'RANGKA LANTAI',
                'kode_kit' => 'A01',
                'KIT' => 'KIT STALL 1 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH,4 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1002',
                'nama_komponen' => 'PLAT LANTAI ',
                'kode_kit' => 'A01',
                'KIT' => 'KIT STALL 1 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH ',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1003',
                'nama_komponen' => 'PIPA SLANGER',
                'kode_kit' => 'A01',
                'KIT' => 'KIT STALL 1 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1004',
                'nama_komponen' => 'PLAT HITAM 2 X 75 X 60',
                'kode_kit' => 'A01',
                'KIT' => 'KIT STALL 1 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1005',
                'nama_komponen' => 'PLAT BIBIRAN LANTAI ',
                'kode_kit' => 'A01',
                'KIT' => 'KIT STALL 1 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                    'tipe_FEL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1006',
                'nama_komponen' => 'BRACKET BUMPER DEPAN NEW ELF',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1007',
                'nama_komponen' => 'PANEL RH ASSY',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1008',
                'nama_komponen' => 'PENAHAN LUMPUR LH NEW ELF',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1009',
                'nama_komponen' => 'PENAHAN LUMPUR RH NEW ELF',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1010',
                'nama_komponen' => 'PIPA KOTAK',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1011',
                'nama_komponen' => 'INNER PANEL TENGAH',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1012',
                'nama_komponen' => 'PINTU PENUMPANG KE-1 ',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1013',
                'nama_komponen' => 'PINTU PENUMPANG KE-2',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1014',
                'nama_komponen' => 'PINTU BBM',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1015',
                'nama_komponen' => 'RUMAH ENGSEL TUTUP BBM',
                'kode_kit' => 'A02',
                'KIT' => 'KIT STALL 2 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1016',
                'nama_komponen' => 'TRAP',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1017',
                'nama_komponen' => 'TRAP ELF DEPAN',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1018',
                'nama_komponen' => 'TRAP ELF BELAKANG',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1019',
                'nama_komponen' => 'TRAP',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1020',
                'nama_komponen' => 'TRAP ELF DEPAN',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1021',
                'nama_komponen' => 'TRAP ELF BELAKANG',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1022',
                'nama_komponen' => 'TRAP DEPAN (1 STEP)',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1023',
                'nama_komponen' => 'TRAP BELAKANG (1 STEP)',
                'kode_kit' => 'A03', 'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1024',
                'nama_komponen' => 'CAGAK PANEL NEW ELF PANJANG (KHUSUS 5P)',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1025',
                'nama_komponen' => 'CAGAK PANEL NEW ELF SEDANG (KHUSUS 5P)',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1026',
                'nama_komponen' => 'CAGAK PANEL NEW ELF PENDEK (KHUSUS 5P)',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1027',
                'nama_komponen' => 'BAGASI TOOLKIT',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING', 'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1028',
                'nama_komponen' => 'RUMAH ENGSEL TUTUP BBM',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1029',
                'nama_komponen' => 'SEAT REAR BUMPER / SUPPORT BUMPER (NEW ELF) RH',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1030',
                'nama_komponen' => 'SEAT REAR BUMPER / SUPPORT BUMPER (NEW ELF) LH',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1031',
                'nama_komponen' => 'SEAT BUMPER BELAKANG',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1032',
                'nama_komponen' => 'BRACKET BUMPER BELAKANG',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1033',
                'nama_komponen' => 'BAUT BH 8X25',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1034',
                'nama_komponen' => 'RING PLAT WP 8',
                'kode_kit' => 'A03',
                'KIT' => 'KIT STALL 3 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1035',
                'nama_komponen' => 'PIPA PENGUAT PBA ',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1036',
                'nama_komponen' => 'PANEL PBA ASSY',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1037',
                'nama_komponen' => 'PENGUAT CAGAK I',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1038',
                'nama_komponen' => 'INNER PILLAR I (ELF)',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1039',
                'nama_komponen' => 'AIR INTAKE',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1040',
                'nama_komponen' => 'INNER PILAR B RH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1041',
                'nama_komponen' => 'INNER PINTU STECKER LH NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1042',
                'nama_komponen' => 'INNER PINTU SPASI LH NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1043',
                'nama_komponen' => 'INNER PILAR STECKER BAGIAN ATAS',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1044',
                'nama_komponen' => 'INNER PILAR SUNDUK BAGIAN ATAS',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1045',
                'nama_komponen' => 'PENGUAT PANEL / SENDENGAN FUSO (KECIL)',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1046',
                'nama_komponen' => 'CONNECTOR SAMPING ROOF A LH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1047',
                'nama_komponen' => 'CONNECTOR SAMPING ROOF B LH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1048',
                'nama_komponen' => 'CONNECTOR SAMPING ROOF A RH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1049',
                'nama_komponen' => 'CONNECTOR SAMPING ROOF B RH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1050',
                'nama_komponen' => 'ROOF A (NEW ELF) /MIDDLE ROOF (LONG/SHORT) 1300X3000',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1051',
                'nama_komponen' => 'ROOF B (NEW ELF) /MIDDLE ROOF (LONG) 1300X2700',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1052',
                'nama_komponen' => 'CONNECTOR KAP SHR RH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1053',
                'nama_komponen' => 'CONNECTOR KAP SHR LH',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1054',
                'nama_komponen' => 'CONNECTOR DEPAN NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1055',
                'nama_komponen' => 'TUTUP MESIN ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1056',
                'nama_komponen' => 'INNER BELAKANG TUTUP MESIN RH NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1057',
                'nama_komponen' => 'INNER RH I',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1058',
                'nama_komponen' => 'SAMBUNGAN KNALPOT',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1059',
                'nama_komponen' => 'RANGKA AKI',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1060',
                'nama_komponen' => 'PLAT ACCU BAWAH NEW ELF LONG',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1061',
                'nama_komponen' => 'PLAT ACCU BELAKANG NEW ELF LONG',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1062',
                'nama_komponen' => 'PLAT ACCU LH NEW ELF LONG',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1063',
                'nama_komponen' => 'PLAT ACCU RH NEW ELF LONG',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1064',
                'nama_komponen' => 'BAUT RUMAH ACCU BH 8X25',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1065',
                'nama_komponen' => 'RING PLAT WP 8',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1066',
                'nama_komponen' => 'FRAME HOUSING TUTUP BBM LH NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1067',
                'nama_komponen' => 'FRAME HOUSING TUTUP BBM RH NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1068',
                'nama_komponen' => 'PIPA PENYANGGA BELAKANG',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1069',
                'nama_komponen' => 'SIKU PENGUAT PADA RUMAH ENGSEL PBA',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1070',
                'nama_komponen' => 'INNER PILLAR BELAKANG PBA LH FUSO',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1071',
                'nama_komponen' => 'INNER PILLAR BELAKANG PBA RH FUSO',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMRL1072',
                'nama_komponen' => 'TUTUP ENGSEL PBA NEW ELF',
                'kode_kit' => 'A04',
                'KIT' => 'KIT STALL 4 BODY WELDING',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => '5 PINTU PISAH',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'kode_komponen' => 'J02SMPRL2001',
                'nama_komponen' => 'TUTUP TRAP',
                'kode_kit' => '',
                'KIT' => '',
                'kode_mobil' => [
                    'tipe_EL' => true,
                ],
                'parameter_1' => 'PASANG TUTUP TRAP',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],


        ]);
    }
}
