USE [DATABASENAME]
GO

/****** Object:  Table [dbo].[SURATPERINTAHKERJA]    Script Date: 10/13/2022 10:32:41 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SURATPERINTAHKERJA](
	[SPK Number] [char](31) NOT NULL,
	[Merk] [char](61) NOT NULL,
	[Type] [char](61) NOT NULL,
	[No Rangka] [char](61) NOT NULL,
	[No Mesin] [char](61) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


